### ISSUE TITLE
Can I train the model with test.tar.zst ?

### ISSUE THREAD

**Issue by haoink** [uzh-rpg/snn_angular_velocity#1]
Hello, I am in the beginning phase to learn how to train SNN with Slayer framework. And I find this project a very good resource. I went through your code but I can't find the code to train the model. Did I make a mistake or can you make this part of code available (if possible). Thanks!

**Comment by magehrig** [comment]
Hi, thanks for your interest. Currently only the test code is available. It is still my intention to release the training code but was unable to do so due to time constraints

**Comment by haoink** [comment]
Thanks anyways
