### ISSUE TITLE
What GPU are you using?

### ISSUE THREAD

**Issue by oshima-yoppi** [uzh-rpg/snn_angular_velocity#9]
Hi!
What a wonderful study! Thank you for uploading your codes to github.

When building a neural network, I assume that the time series data from the event camera uses a lot of memory. Have you encountered any GPU memory errors? If you don't mind, I would like to know the model and number of GPUs you are using.

**Comment by magehrig** [comment]
Sorry for the late response. I was using an RTX 2080 Ti at that point for the experiments (11 GB).
